### ISSUE TITLE
The C++ FQA is a historical document about C++98

### ISSUE THREAD

**Issue by ab396356** [yosefk/cpp-fqa#11]
### Purpose ###

While the "high-level" criticisms of the language are still accurate today (the "Defective C++" summary) a lot of the quirks and missing features pounced on by the FQA have been resolved since C++98, and the purpose of this post is to list them.

With that in mind, I believe the FQA is more valuable (and entertaining) as a historical document criticizing C++98 strictly (particularly because the [Parashift C++ FAQ](http://web.archive.org/web/20120610233050/http://www.parashift.com/c++-faq/) is now historical as well), lest we forget the ugly duckling that C++ used to be.

----

### List of C++98 issues ###

* [No reflection](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/defective.fqa#L148)
  C++11 added the [`decltype`](http://en.cppreference.com/w/cpp/language/decltype) specifier and the [_typeindex_](http://en.cppreference.com/w/cpp/header/typeindex) and [_type_traits_](http://en.cppreference.com/w/cpp/header/type_traits) libraries.

* [Unhelpful standard library](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/defective.fqa#L442) and
  [[15.16] Why can't I open a file in a different directory such as `"..\test.dat"`?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/io.fqa#L306)

  > The standard library doesn't support listing directories

  > unlike the fact that the C++ standard library has no way to _open a directory_, for example.

  C++17 will add the [_filesystem_](http://en.cppreference.com/w/cpp/filesystem) library, by stealing code from [_Boost.Filesystem_](http://www.boost.org/doc/libs/release/libs/filesystem/).

* [Unhelpful standard library](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/defective.fqa#L442)

  > Well, the standard library doesn't have matrices or regular expressions, either.

  C++11 added the [_regex_](http://en.cppreference.com/w/cpp/regex) library.

* [[6.16] Will I sometimes use any so-called "evil" constructs?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/picture.fqa#L297) and
  [[16.20] Does C++ have arrays whose length can be specified at run-time?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/heap.fqa#L364)

  > Note that with evil arrays, you can write `int a[3] = {1,2,3};` while with the supposedly less evil `std::vector`, you can't.

  > `std::vector` is not an array, it's a class that looks like an array until you try to initialize it with `{1,2,3}` or pass an array to a function expecting a `vector` or get a huge compiler error message.

  C++11 added [uniform initialization](http://www.stroustrup.com/C++11FAQ.html#init-list) by way of [`std::initializer_list`](http://en.cppreference.com/w/cpp/utility/initializer_list).

* [[6.18] What should I tell people who complain that the word "FAQ" is misleading, that it emphasizes the questions rather than the answers, and that we should all start using a different acronym?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/picture.fqa#L327)

  > For example, why would someone deprecate `static` variables at the translation unit scope and demand people to use anonymous namespaces to get identical behavior?

  C++11 [reversed the decision](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1012) to deprecate `static` for this usage.

* [[10.3] Can one constructor of a class call another constructor of the same class to initialize the `this` object?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/ctors.fqa#L45)
  C++11 added support for [delegating constructors](http://www.stroustrup.com/C++11FAQ.html#delegating-ctor).

* [[10.5] Which constructor gets called when I create an array of `Fred` objects?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/ctors.fqa#L71) and
  [[16.11] How do I allocate / unallocate an array of things?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/heap.fqa#L209) and
  [[33.6] How do I create and use an array of pointer-to-member-function?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/function.fqa#L159)

  > And there's no standard container you can use for allocating memory on the stack, for example, so if you want one, you'll have to write it yourself.

  > Alternatively, if you'd rather create a problem than solve one, you can replace your evil arrays with `std::vector`.

  > Hey, why are we using an evil C array? Me not like this. How about:
  >
  > ```c++
  > std::vector<FuncPtrType> arr;
  > arr.push_back(&C::f);
  > arr.push_back(&C::g);
  > arr.push_back(&C::h);
  > ```

  C++11 added the [`std::array`](http://en.cppreference.com/w/cpp/container/array) container.
  (Repeat) C++11 added [uniform initialization](http://www.stroustrup.com/C++11FAQ.html#init-list) by way of [`std::initializer_list`](http://en.cppreference.com/w/cpp/utility/initializer_list).

* [[10.9] Does return-by-value mean extra copies and extra overhead?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/ctors.fqa#L138)
  C++11 added [`std::move`](http://en.cppreference.com/w/cpp/utility/move) semantics and [rvalue references](http://thbecker.net/articles/rvalue_references/section_01.html).

* [[13.6] Can I overload `operator==` so it lets me compare two `char[]` using a string comparison?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/operator.fqa#L175)

  > As to the "arrays are evil" mantras - how about chanting them to the authors of the C++ standard library that defined an `std::ifstream` constructor accepting `const char*`, but not `std::string`? And they didn't define an operator `const char*` in `std::string`, either. `std::ifstream in((std::string(dir) + "/" + file).c_str());`. Give me a break.

  C++11 added [`std::string` overloads](http://en.cppreference.com/w/cpp/io/basic_ifstream/basic_ifstream) for file stream constructors.
  C++11 added [user-defined literals](http://www.stroustrup.com/C++11FAQ.html#UD-literals) and C++14 added `std::string` literals aka [`std::literals::string_literals::operator""s`](http://en.cppreference.com/w/cpp/string/basic_string/operator%22%22s).

* [[15.4] How does that funky `while (std::cin >> foo)` syntax work?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/io.fqa#L111)

  > Why is it `operator void*`, and not `operator bool`?

  C++11 updated streams to use [`explicit operator bool()`](http://en.cppreference.com/w/cpp/io/basic_ios/operator_bool), which being marked `explicit` has the potential to [break some code](http://coliru.stacked-crooked.com/a/9ebc91e8b91ef83d).

* [[20.1] What is a "`virtual` member function"?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/inheritance-virtual.fqa#L5)

  > you can't look at a derived class and say which functions are `virtual` (the keyword is optional), and overloading makes it even harder to see when a function actually overrides a base class implementation

  C++11 added the [`override`](http://en.cppreference.com/w/cpp/language/override) specifier.

* [[20.6] I have a heterogeneous list of objects, and my code needs to do class-specific things to the objects. Seems like this ought to use dynamic binding but I can't figure it out. What should I do?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/inheritance-virtual.fqa#L164)

  > Off-topic: the STL way of saying `foreach p in shapes` is pretty ugly, isn't it? 

  C++11 added the [range-based `for()` loop](http://en.cppreference.com/w/cpp/language/range-for).

* [[23.11] How can I set up my class so it won't be inherited from?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/inheritance-mother.fqa#L311)

  > C++ doesn't have `final`.

  C++11 added the [`final`](http://en.cppreference.com/w/cpp/language/final) specifier.

* [[33.10] What the heck is a functionoid, and why would I use one?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/function.fqa#L223)
  C++11 added [lambda functions](http://www.stroustrup.com/C++11FAQ.html#lambda) aka [closures](http://en.cppreference.com/w/cpp/language/lambda).

* [[35.2] What's the syntax / semantics for a "class template"?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/templates.fqa#L52)

  > Oh, and when you want to use a template, be kind with the C++ lexer (the part of the compiler converting text to "tokens" so that the parser can check whether they make meaningful statements). Code like `vector<vector<int>>`, which tries to declare an inefficient implementation of a 2D array, won't compile - you need a space before the two > characters.

  C++11 fixed the [right angle brackets](http://www.stroustrup.com/C++11FAQ.html#brackets).

----

### Personal notes ###

* [[6.2] Is C++ a perfect language?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/picture.fqa#L27)

  > However, despite the obsession with perfection, C++ _is_ "practical" - from a language designer's perspective rather than from a user's point of view. The "practical" thing in C++ is that it's based on C. This helped the language gain popularity. This is also the main reason for inconsistencies in the language - ambiguities in the grammar (declaration/definition, type name/object name...), duplications of functionality in the different features (pointers/references, constructors/aggregate initialization, macros/constants/templates, files/namespaces...). C++ sacrifices consistency for popularity. This "practical" approach helps to increase the number of C++ users, but it doesn't help those users to get their job done.

  This point is repeated throughout the FQA a couple of times, and I believe there may be some validity to it.

  Whenever C++ is presented as a higher-level and superior alternative to C, remind yourself how your program explodes with a Segmentation Fault if you invalidate the iterators of a standard container such as `std::map` and try to use them. You'd at least expect an exception to be thrown, right?

* [[19.3] How do you express inheritance in C++?](https://github.com/yosefk/cpp-fqa/blob/c638d3a673aa0534c7dd09359a10a5ba9673e7f5/inheritance-basics.fqa#L59)

  > You may wonder what the colon syntax has to do with the concept of inheritance. Well, the connection is obvious: there's no inheritance in C, and adding keywords to C++ reduces the "compatibility" with C, because the grammars of these languages prevent you from using keywords as identifiers. Once again, punctation comes to the rescue. The other technique for retro-fitting features into the grammar is overloading keywords (consider `static`).

  I hear that! Also consider C++11 and the "keyword-less" syntax of [lambda functions](http://en.cppreference.com/w/cpp/language/lambda) and the reuse of [`auto`](http://en.cppreference.com/w/cpp/language/auto), [`delete`](http://en.cppreference.com/w/cpp/language/function#Deleted_functions), [`default`](http://en.cppreference.com/w/cpp/language/member_functions#Special_member_functions) and [`using`](http://en.cppreference.com/w/cpp/language/type_alias) and then remember about the introduction of [`constexpr`](http://en.cppreference.com/w/cpp/language/constexpr), [`decltype`](http://en.cppreference.com/w/cpp/language/decltype), [`nullptr`](http://en.cppreference.com/w/cpp/language/nullptr), [`noexcept`](http://en.cppreference.com/w/cpp/language/noexcept_spec), [`override`](http://en.cppreference.com/w/cpp/language/override), [`final`](http://en.cppreference.com/w/cpp/language/final), and more...

**Comment by yosefk** [comment]
I agree that the C++ FQA is about C++98 and not the later revisions _right now_, but I disagree with the opinion that it _should be_, for several reasons:

1. Neither the FQA nor, dare I say, C++98 are of much historical significance - so as long as the FQA remains a document about C++98 it's simply not very interesting;
2. C++ still sucks;
3. Its competition is tougher than ever (plenty of new statically typed garbage-collected languages and then Rust, C++'s closest competitor);
4. C++ apologists are louder than ever, overstating the benefits of C++11/14/17, downplaying the drawbacks and rebranding this shit as "Modern C++" when in fact it's the same tired arguments along the lines of Real Men with Smart Pointers Everywhere Don't Need GC (and cyclical references don't exist and needless copying is not slow or doesn't happen with move constructors blah blah BLAH.)

Obviously the FQA can only move forward if editors come along who strongly believe point 2 and care enough to spend their time educating the public on the subject. Unfortunately, I'm not that guy today - or maybe fortunately for me, because I'm lucky enough to not have to deal with C++ all that much.

But I deal with it enough to know that it sucks in its new incarnations (and I do recommend to upgrade to C++11 and beyond, don't get me wrong, I even campaigned for it where I work. Do upgrade, but it still sucks.) As to your specific points - C++ still doesn't have anything close to reflection, initializer lists are something even Scott Meyers still didn't quite manage to understand, move semantics complicate the language a lot and you'll still have a shitton of unnecessary copying, the lambdas are sometimes better than nothing but it's the only language where two lambdas taking and returning arguments of the same type do NOT have the same type (try declaring an array of lambdas) and don't get me started about the capture lists and capturing dangling references and why everything in this world just blows without garbage collection, etc.

I do agree of course that _some_ problems with C++98 are solved in newer revisions, period - that is, with no downside to speak of; however, these revisions also create new problems altogether. And so I do agree that quite a lot of the FQA must be rewritten, both to fit the new structure of the FAQ and more importantly to adjust to the new map of language problems. And since that's a lot of work, it could very well be that nobody will show up who wants to do it, and then the FQA technically will remain a document about C++98.

But that will still remain a sad fact rather than a goal.

**Comment by ab396356** [comment]
> [...] when in fact it's the same tired arguments along the lines of Real Men with Smart Pointers Everywhere Don't Need GC [...]

For my information, how does one combat the RAII argument when these people have the "GC is not fast" argument already prepared?

> Obviously the FQA can only move forward if editors come along who strongly believe point 2 and care enough to spend their time educating the public on the subject. Unfortunately, I'm not that guy today [...]

If you're waiting for others to "come along" do _your_ work, then your work won't get done. Anyway shouldn't you have more free time on your hands nowadays, since you took up cartoon animation?

I guess I could follow my own list above, and start deleting, deleting, deleting parts of the FQA to bring it up to date. But don't expect me to be able to word criticism of "Modern C++" the way you can (or could, if you weren't lazy).

**Comment by yosefk** [comment]
If you want to combat that argument, a battle-tested response, or at least a good start, is that malloc + shared_ptr (the latter uses 100-cycle atomic increments/decrements) is slower than a GC and still leaks memory when you have cyclic references.

I'm not waiting for others to do my work, where "my work" is defined as "things I get paid to do" (this should also give you a hint wrt what my response to "lazy" or "having more free time" might have been.) If someone wants to write about how much C++11 sucks and they like the FQA form and they'd like use it as a starting point, then I published the source and I'll accept pull requests (or they can fork it) and I'll probably republish the result at the original place, whatever that's worth in terms of PageRank and what-not. If you don't want to do it, then, well, don't do it. And if you think C++11 is the cat's whiskers, then by all means enjoy it, while I enjoy the fact that I don't need to suffer through this shit and no longer care all that much.
